"""Read-only actor facts required for the owner's World feed and thread."""
from typing import Protocol
from app.domains.social.contracts.actors import SocialCharacter
from app.domains.social.contracts.source_writes import SourceWorldCharacter, SourceMembership
from app.domains.world_characters.contracts.owner_identity import OwnerControlledIdentitySnapshot


class ManualFeedWorldCharacter(SourceWorldCharacter, Protocol):
    @property
    def local_profile(self) -> object | None: ...


class ManualFeedReferences(Protocol):
    def prepare_authors(self, *, world_id: str, author_ids: set[str]) -> None: ...
    def get_owner_identity(self, *, world_id: str, current_user_id: str) -> OwnerControlledIdentitySnapshot: ...
    def get_world_character(self, world_character_id: str) -> ManualFeedWorldCharacter | None: ...
    def get_character(self, character_id: str) -> SocialCharacter | None: ...
    def get_membership(self, membership_id: str) -> SourceMembership | None: ...
    def active_author_id(self, *, world_id: str, author_world_character_id: str) -> str | None: ...
