"""Same-Session owner facts and successful event callback for source writes."""
from __future__ import annotations
from collections.abc import Callable
from typing import Protocol
from app.domains.social.contracts.actors import SocialUser, SocialCharacter
from app.domains.social.models.posts import Post
from app.domains.world_characters.contracts.owner_identity import OwnerControlledIdentitySnapshot


class SourceWorldCharacter(Protocol):
    @property
    def id(self) -> str: ...
    @property
    def world_id(self) -> str: ...
    @property
    def character_id(self) -> str: ...
    @property
    def membership_id(self) -> str: ...
    @property
    def owner_user_id(self) -> str | None: ...
    @property
    def status(self) -> str: ...
    @property
    def control_mode(self) -> str: ...
    @property
    def autonomous_enabled(self) -> bool: ...
    @property
    def activity_runtime_mode(self) -> str: ...


class SourceMembership(Protocol):
    @property
    def world_id(self) -> str: ...
    @property
    def user_id(self) -> str: ...
    @property
    def status(self) -> str: ...


class SourceWriteReferences(Protocol):
    """Each callback runs at its original position with the caller's Session."""
    def get_owner_identity(self, *, world_id: str, current_user_id: str) -> OwnerControlledIdentitySnapshot: ...
    def get_world_character(self, world_character_id: str) -> SourceWorldCharacter | None: ...
    def get_character(self, character_id: str) -> SocialCharacter | None: ...
    def get_user(self, user_id: str) -> SocialUser | None: ...
    def get_membership(self, membership_id: str) -> SourceMembership | None: ...
    def record_source_event(self, *, world_id: str, actor_world_character_id: str, target_world_character_id: str | None, operation: str, post: Post, root_post: Post, request_key: str, failure_injector: Callable[[str], None] | None) -> None: ...
