"""Read-only action facts consumed where the declaration is validated.

The concrete objects remain attached to the caller's Session; no value snapshot
or eager lookup is performed when the collaborator is created.
"""

from datetime import datetime
from typing import Protocol
from app.domains.social.contracts.source_writes import SourceWorldCharacter


class SubjectiveExecution(Protocol):
    @property
    def id(self) -> int: ...
    @property
    def signature(self) -> str: ...
    @property
    def status(self) -> str: ...
    @property
    def social_event_id(self) -> str | None: ...
    @property
    def world_id(self) -> str | None: ...
    @property
    def actor_world_character_id(self) -> str | None: ...


class SubjectiveEvent(Protocol):
    @property
    def id(self) -> str: ...
    @property
    def world_id(self) -> str: ...
    @property
    def actor_world_character_id(self) -> str: ...
    @property
    def result(self) -> str: ...
    @property
    def invalidated_at(self) -> datetime | None: ...


class SubjectiveWorld(Protocol):
    @property
    def id(self) -> str: ...
    @property
    def owner_user_id(self) -> str: ...


class SubjectiveEvidence(Protocol):
    @property
    def source_post_id(self) -> str | None: ...
    @property
    def target_post_id(self) -> str | None: ...
    @property
    def root_post_id(self) -> str | None: ...
    @property
    def content_sha256(self) -> str | None: ...


class SubjectiveReferences(Protocol):
    def get_world(self, world_id: str) -> SubjectiveWorld | None: ...
    def get_actor(self, actor_id: str) -> SourceWorldCharacter | None: ...
    def get_evidence(
        self, *, event_id: str, execution_id: int
    ) -> SubjectiveEvidence | None: ...
