"""Attached read views used by activity scope decisions."""
from __future__ import annotations
from typing import Protocol


class ActiveWorldRead(Protocol):
    @property
    def world_character_id(self) -> str: ...


class WorldCharacterRead(Protocol):
    @property
    def character_id(self) -> str: ...
    @property
    def world_id(self) -> str: ...
    @property
    def autonomous_enabled(self) -> bool: ...


class WorldRead(Protocol):
    @property
    def timezone(self) -> str: ...


class ActivityScopeReads(Protocol):
    def has_active_world_table(self) -> bool: ...
    def has_world_character_table(self) -> bool: ...
    def has_world_table(self) -> bool: ...
    def has_import_table(self) -> bool: ...
    def get_active_world(self, character_id: str) -> ActiveWorldRead | None: ...
    def get_world_character(self, world_character_id: str) -> WorldCharacterRead | None: ...
    def get_world(self, world_id: str) -> WorldRead | None: ...
    def get_import_id(self, world_id: str) -> str | None: ...
    def get_latest_imported_world_character(self, character_id: str) -> WorldCharacterRead | None: ...
