"""Read existing related records in the activity caller's transaction."""
from typing import Any, Protocol


class ActivityReferences(Protocol):
    def get_world_character(self, world_character_id: str, *, lock_for_update: bool = False) -> Any: ...
    def get_membership(self, membership_id: str) -> Any: ...
    def get_post(self, post_id: str) -> Any: ...
