"""Lazy scope and canonical Social facts used by resident feed note policy."""

from typing import Any, Protocol
from sqlalchemy.orm import Session
from app.domains.routines.contracts.feed_history import FeedHistoryReferences


class NoteRun(Protocol):
    @property
    def id(self) -> str: ...
    @property
    def user_id(self) -> str: ...
    @property
    def character_id(self) -> str: ...
    @property
    def post_id(self) -> str | None: ...


class NotePost(Protocol):
    @property
    def id(self) -> str: ...


class FeedHistoryNoteReferences(Protocol):
    @property
    def history(self) -> FeedHistoryReferences: ...
    @property
    def authorization_error(self) -> type[Exception]: ...
    def authorize(self, db: Session, *, session_key: str, action: str) -> NoteRun: ...
    def get_post(self, db: Session, post_id: str) -> NotePost | None: ...
    def is_public_context_visible(self, db: Session, post: NotePost) -> bool: ...
    def normalize_post_seed_intent(
        self, value: Any, *, post_seed: Any = None
    ) -> str: ...
