"""Attached Social post facts and lazy reads used to assemble resident history."""

from __future__ import annotations
from datetime import datetime
from typing import Protocol
from sqlalchemy.orm import Session


class HistoryPost(Protocol):
    @property
    def id(self) -> str: ...
    @property
    def title(self) -> str | None: ...
    @property
    def body(self) -> str | None: ...
    @property
    def author_name(self) -> str | None: ...
    @property
    def created_at(self) -> datetime: ...


class FeedHistoryReferences(Protocol):
    def get_post(self, db: Session, post_id: str) -> HistoryPost | None: ...
    def is_eligible(
        self, db: Session, *, character_id: str, post: HistoryPost
    ) -> bool: ...
    def public_visible(self, db: Session, post: HistoryPost) -> bool: ...
    def topic_metadata(
        self, db: Session, *, post: HistoryPost, character_id: str | None = None
    ) -> dict[str, str]: ...
    def recent_roots(
        self, db: Session, *, character_id: str, cutoff: datetime, limit: int
    ) -> list[HistoryPost]: ...
    def body_preview(self, value: str | None) -> str: ...
    def fallback_topic(self, *, title: str | None, body: str | None) -> str: ...
    def is_feed_theme(self, value: object) -> bool: ...
