"""Queries used by the existing preferred/scoped/fallback target policy."""
from typing import Protocol


class PostSelectionReferences(Protocol):
    def get_latest_visible_nonself_root_id(self, character_id: str) -> str | None: ...
    def get_latest_visible_root_id(self) -> str | None: ...
    def routine_world_character_for_character(self, *, character_id: str) -> object | None: ...
