"""Foreign reads needed by the existing SQL-owning slot workflows."""
from __future__ import annotations
from datetime import datetime
from zoneinfo import ZoneInfo
from typing import Protocol
from sqlalchemy.sql.elements import ColumnElement


class SlotCharacterRead(Protocol):
    @property
    def deleted_at(self) -> datetime | None: ...
    @property
    def moderation_status(self) -> str: ...


class SlotReferences(Protocol):
    def lock_character_id(self, character_id: str) -> str | None: ...
    def owner_controlled_predicate(self) -> ColumnElement[bool]: ...
    def get_character(self, character_id: str) -> SlotCharacterRead | None: ...
    def capture_activity_input(self, character_id: str) -> dict | None: ...
    def activity_configuration_for_input(self, metadata: dict | None, *, character_id: str) -> AdmittedActivityConfiguration | None: ...
    def effective_settings_for_input(self, setting: object, metadata: dict | None, *, character_id: str) -> object: ...
    def activity_timezone(self, character_id: str) -> ZoneInfo: ...


class AdmittedActivityConfiguration(Protocol):
    """Only admitted schedule values needed by Routine's claim policy."""
    autonomous_enabled: bool
    settings: object
