"""Temporary aliases for surviving legacy Chat imports; no workflow lives here."""
from app.domains.chat.policies import API_KEY_INVALID_MESSAGE, API_KEY_MISSING_MESSAGE, CHARACTER_DISABLED_MESSAGE, CONTEXT_CHAR_LIMIT, CONTEXT_MESSAGE_LIMIT, DEFAULT_MESSAGE_MODEL, LOCAL_CHARACTER_MESSAGES_DISABLED_MESSAGE, MAX_ACTIVE_THREADS, MESSAGE_MODELS, MESSAGE_RESPONSE_LEASE_SECONDS, MODEL_BUSY_MESSAGE, MODEL_OUTPUT_TOKENS, PROMPT_INJECTION_BLOCKED_MESSAGE, THREAD_LIMIT_MESSAGE, USER_MESSAGE_LIMIT
from app.domains.chat.exceptions import MessageCredentialInvalidError, MessageCredentialRequiredError, MessageForbiddenError, MessageInFlightError, MessageModelBusyError, MessageNotFoundError, MessageServiceError, MessageThreadLimitError, MessageValidationError
from app.core import security
from sqlalchemy.exc import IntegrityError
from app.integrations.direct_llm import DirectLlmError
from app.domains.chat.service.threads import LEGACY_WORLD_THREAD_MUTATION_MESSAGE, LEGACY_LOCAL_THREAD_CREATION_MESSAGE
from app.domains.chat.service import profiles
from app.runtime.chat.message_composition import settings_service, thread_service, message_service

_user_ref = profiles._user_ref
_get_owned_character = profiles._get_owned_character
_character_ref = profiles._character_ref
_get_character = profiles._get_character
_owned_agent_refs = profiles._owned_agent_refs
get_user_settings = settings_service.get_user_settings
update_character_message_settings = settings_service.update_character_message_settings
_upsert_message_credential = settings_service._upsert_message_credential
update_user_settings = settings_service.update_user_settings
ensure_user_preference = settings_service.ensure_user_preference
_has_usable_credential = settings_service._has_usable_credential
get_character_message_settings = settings_service.get_character_message_settings
_get_message_credential = settings_service._get_message_credential
_ensure_character_available_for_messages = settings_service._ensure_character_available_for_messages
resolve_message_credential_material = settings_service.resolve_message_credential_material
_ensure_supported_model = settings_service._ensure_supported_model
_get_agent_source_credential = settings_service._get_agent_source_credential
ensure_character_setting = settings_service.ensure_character_setting
_resolve_message_credential = settings_service._resolve_message_credential
_generate_message_answer = message_service._generate_message_answer
_message_output_prompt_injection_block = message_service._message_output_prompt_injection_block
_retry_message_locked = message_service._retry_message_locked
_build_system_prompt = message_service._build_system_prompt
_release_response_lease = message_service._release_response_lease
_build_user_prompt = message_service._build_user_prompt
_llm_failure_message = message_service._llm_failure_message
_send_message_locked = message_service._send_message_locked
retry_message = message_service.retry_message
_acquire_response_lease = message_service._acquire_response_lease
send_message = message_service.send_message
_owner_controlled_world_characters = thread_service._owner_controlled_world_characters
get_world_thread = thread_service.get_world_thread
_world_thread_read = thread_service._world_thread_read
list_world_threads = thread_service.list_world_threads
_get_owned_legacy_mutable_thread = thread_service._get_owned_legacy_mutable_thread
create_or_get_world_thread = thread_service.create_or_get_world_thread
list_threads = thread_service.list_threads
_require_world_chat_owner_scope = thread_service._require_world_chat_owner_scope
_world_characters_are_blocked = thread_service._world_characters_are_blocked
_get_owned_world_thread = thread_service._get_owned_world_thread
_legacy_thread_read = thread_service._legacy_thread_read
_get_owned_thread = thread_service._get_owned_thread
_ensure_no_active_world_response_request = thread_service._ensure_no_active_world_response_request
resolve_world_thread_response_model = thread_service.resolve_world_thread_response_model
_active_responding_world_character = thread_service._active_responding_world_character
_claimed_local_installation_exists = thread_service._claimed_local_installation_exists
_world_chat_role = thread_service._world_chat_role
_latest_thread_message = thread_service._latest_thread_message
get_world_chat_entry = thread_service.get_world_chat_entry
get_thread = thread_service.get_thread
update_thread = thread_service.update_thread
update_world_thread_model = thread_service.update_world_thread_model
create_or_get_thread = thread_service.create_or_get_thread
_thread_evidence_summaries = thread_service._thread_evidence_summaries
_thread_messages = thread_service._thread_messages
_thread_read = thread_service._thread_read
delete_thread = thread_service.delete_thread
_find_active_world_thread = thread_service._find_active_world_thread
_is_postgresql_session = thread_service._is_postgresql_session
_lock_message_thread_quota = thread_service._lock_message_thread_quota
_lock_world_thread_tuple = thread_service._lock_world_thread_tuple

generate_text = message_service.generate_text
