x-backend-ci-image: &backend-ci-image angmoo-backend-ci:${ANGMOO_CI_IMAGE_TAG:-ci}

services:
  backend:
    image: *backend-ci-image
    pull_policy: never

  frontend:
    image: angmoo-frontend-ci:${ANGMOO_CI_IMAGE_TAG:-ci}
    pull_policy: never
