"""Compatibility facade for the canonical routines domain."""

from app.domains.routines.public import (
    DAYPARTS,
    DAYPART_START_HOURS,
    EVENT_CONSUMPTION_NAMESPACE,
    INITIAL_STATE,
    RECENT_EXACT_DAYS,
    SELECTION_CONTRACT_VERSION,
    TIMEZONE_CONTRACT_VERSION,
    USAGE_WINDOW_DAYS,
    DailyActivityPlanConflictError,
    DailyActivityPlanError,
    DailyActivityPlanForbiddenError,
    DailyActivityPlanNotFoundError,
    DailyActivityPlanValidationError,
    PlanScope,
    daypart_windows,
    get_activity_plan,
    local_activity_date,
    prepare_activity_plan,
    update_activity_runtime_mode,
)

__all__ = [
    "DAYPARTS",
    "DAYPART_START_HOURS",
    "EVENT_CONSUMPTION_NAMESPACE",
    "INITIAL_STATE",
    "RECENT_EXACT_DAYS",
    "SELECTION_CONTRACT_VERSION",
    "TIMEZONE_CONTRACT_VERSION",
    "USAGE_WINDOW_DAYS",
    "DailyActivityPlanConflictError",
    "DailyActivityPlanError",
    "DailyActivityPlanForbiddenError",
    "DailyActivityPlanNotFoundError",
    "DailyActivityPlanValidationError",
    "PlanScope",
    "daypart_windows",
    "get_activity_plan",
    "local_activity_date",
    "prepare_activity_plan",
    "update_activity_runtime_mode",
]
