"""Stable public surface for social discovery and canonical source writes."""

from __future__ import annotations

from app.domains.social.application import (
    KeywordPostLookup,
    SocialSearchBinding,
    apply_validated_autonomous_result,
    create_owner_post,
    create_owner_reply,
    current_social_search,
    find_keyword_post_ids,
    observe_social_source,
    read_world_character_social_profile,
    register_social_search,
    unregister_social_search,
)
from app.domains.social.domain import (
    ObservationLane,
    OwnerPostCommand,
    OwnerReplyCommand,
    SocialObservationCommand,
    SocialObservationError,
    SocialObservationResult,
    SocialSearchState,
    SocialSearchUnavailable,
    SocialWriteConflictError,
    SocialWriteError,
    SocialWriteForbiddenError,
    SocialWriteNotFoundError,
    SocialWriteResult,
    SocialWriteRetryableError,
    ValidatedAutonomousWriteCommand,
    WorldCharacterSocialProfileCounts,
    WorldCharacterSocialProfileError,
    WorldCharacterSocialProfileForbiddenError,
    WorldCharacterSocialProfileMedia,
    WorldCharacterSocialProfileMention,
    WorldCharacterSocialProfileNotFoundError,
    WorldCharacterSocialProfilePage,
    WorldCharacterSocialProfilePost,
    WorldCharacterSocialProfileQuery,
    WorldCharacterSocialProfileTab,
    WorldCharacterSocialProfileValidationError,
)
from app.domains.social.domain.inbox import ManualInboxInteractionCandidate
from app.domains.social.ports import (
    SocialObservationUnitOfWorkPort,
    SocialSearchIndexPort,
    SocialWriteUnitOfWorkPort,
    WorldCharacterSocialProfileReader,
)

apply_validated_autonomous_social_result = apply_validated_autonomous_result


__all__ = [
    "KeywordPostLookup",
    "ManualInboxInteractionCandidate",
    "ObservationLane",
    "OwnerPostCommand",
    "OwnerReplyCommand",
    "SocialObservationCommand",
    "SocialObservationError",
    "SocialObservationResult",
    "SocialObservationUnitOfWorkPort",
    "SocialSearchBinding",
    "SocialSearchIndexPort",
    "SocialSearchState",
    "SocialSearchUnavailable",
    "SocialWriteConflictError",
    "SocialWriteError",
    "SocialWriteForbiddenError",
    "SocialWriteNotFoundError",
    "SocialWriteResult",
    "SocialWriteRetryableError",
    "SocialWriteUnitOfWorkPort",
    "ValidatedAutonomousWriteCommand",
    "WorldCharacterSocialProfileCounts",
    "WorldCharacterSocialProfileError",
    "WorldCharacterSocialProfileForbiddenError",
    "WorldCharacterSocialProfileMedia",
    "WorldCharacterSocialProfileMention",
    "WorldCharacterSocialProfileNotFoundError",
    "WorldCharacterSocialProfilePage",
    "WorldCharacterSocialProfilePost",
    "WorldCharacterSocialProfileQuery",
    "WorldCharacterSocialProfileReader",
    "WorldCharacterSocialProfileTab",
    "WorldCharacterSocialProfileValidationError",
    "apply_validated_autonomous_social_result",
    "create_owner_post",
    "create_owner_reply",
    "current_social_search",
    "find_keyword_post_ids",
    "observe_social_source",
    "read_world_character_social_profile",
    "register_social_search",
    "unregister_social_search",
]
