"""Stable public surface for social discovery and canonical source writes."""

from __future__ import annotations

from app.domains.social.service.keyword_feed import KeywordPostLookup, find_keyword_post_ids
from app.domains.social.application import apply_validated_autonomous_result, create_owner_post, create_owner_reply, observe_social_source
from app.domains.social.contracts import (
    ACTION_SUBJECTIVE_CONTEXT_VERSION,
    ActionEmotionLabel,
    ActionMotivationKind,
    ActionSubjectiveContextV1,
    SubjectiveContextContractError,
    SubjectiveContextProvenance,
    TodaySocialActivityKind,
    TodaySocialActivityRead,
    TodaySocialActivityRecord,
    TodaySocialCoverageStatus,
    TodaySocialSubjectiveRecord,
    ObservationLane,
    OwnerPostCommand,
    OwnerReplyCommand,
    SocialObservationCommand,
    SocialObservationError,
    SocialObservationResult,
    SocialSearchState,
    SocialSearchUnavailable,
    SocialWriteConflictError,
    SocialWriteError,
    SocialWriteForbiddenError,
    SocialWriteNotFoundError,
    SocialWriteResult,
    SocialWriteRetryableError,
    ValidatedAutonomousWriteCommand,
    WorldCharacterSocialProfileCounts,
    WorldCharacterSocialProfileError,
    WorldCharacterSocialProfileForbiddenError,
    WorldCharacterSocialProfileMedia,
    WorldCharacterSocialProfileMention,
    WorldCharacterSocialProfileNotFoundError,
    WorldCharacterSocialProfilePage,
    WorldCharacterSocialProfilePost,
    WorldCharacterSocialProfileQuery,
    WorldCharacterSocialProfileTab,
    WorldCharacterSocialProfileValidationError,
)
from app.domains.social.contracts.inbox import ManualInboxInteractionCandidate
from app.domains.social.ports import SocialObservationUnitOfWorkPort, SocialWriteUnitOfWorkPort
from app.domains.social.contracts.search_index import SocialSearchIndexPort

apply_validated_autonomous_social_result = apply_validated_autonomous_result


__all__ = [
    "ACTION_SUBJECTIVE_CONTEXT_VERSION",
    "ActionEmotionLabel",
    "ActionMotivationKind",
    "ActionSubjectiveContextV1",
    "SubjectiveContextContractError",
    "SubjectiveContextProvenance",
    "TodaySocialActivityKind",
    "TodaySocialActivityRead",
    "TodaySocialActivityRecord",
    "TodaySocialCoverageStatus",
    "TodaySocialSubjectiveRecord",
    "KeywordPostLookup",
    "ManualInboxInteractionCandidate",
    "ObservationLane",
    "OwnerPostCommand",
    "OwnerReplyCommand",
    "SocialObservationCommand",
    "SocialObservationError",
    "SocialObservationResult",
    "SocialObservationUnitOfWorkPort",
    "SocialSearchIndexPort",
    "SocialSearchState",
    "SocialSearchUnavailable",
    "SocialWriteConflictError",
    "SocialWriteError",
    "SocialWriteForbiddenError",
    "SocialWriteNotFoundError",
    "SocialWriteResult",
    "SocialWriteRetryableError",
    "SocialWriteUnitOfWorkPort",
    "ValidatedAutonomousWriteCommand",
    "WorldCharacterSocialProfileCounts",
    "WorldCharacterSocialProfileError",
    "WorldCharacterSocialProfileForbiddenError",
    "WorldCharacterSocialProfileMedia",
    "WorldCharacterSocialProfileMention",
    "WorldCharacterSocialProfileNotFoundError",
    "WorldCharacterSocialProfilePage",
    "WorldCharacterSocialProfilePost",
    "WorldCharacterSocialProfileQuery",
    "WorldCharacterSocialProfileTab",
    "WorldCharacterSocialProfileValidationError",
    "apply_validated_autonomous_social_result",
    "create_owner_post",
    "create_owner_reply",
    "find_keyword_post_ids",
    "observe_social_source",
]
