"""Frozen additive episode/thought schema; no historical reprocessing."""
from alembic import op

revision = "20260916_0093"
down_revision = "20260914_0092"
branch_labels = None
depends_on = None

SQLITE = (
    "CREATE TABLE chat_message_thoughts (\n\tmessage_id INTEGER NOT NULL, \n\trequest_id VARCHAR(64) NOT NULL, \n\tthought_text TEXT, \n\tstatus VARCHAR(16) NOT NULL, \n\ttruncated BOOLEAN NOT NULL, \n\tsource_digest VARCHAR(64) NOT NULL, \n\tcreated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tPRIMARY KEY (message_id), \n\tCONSTRAINT ck_chat_thought_status CHECK (status IN ('recorded','missing','invalid')), \n\tFOREIGN KEY(request_id) REFERENCES chat_response_requests (request_id) ON DELETE CASCADE, \n\tCONSTRAINT uq_chat_thought_request UNIQUE (request_id), \n\tCONSTRAINT ck_chat_thought_content CHECK ((status = 'recorded' AND thought_text IS NOT NULL AND length(trim(thought_text)) BETWEEN 1 AND 280) OR (status <> 'recorded' AND thought_text IS NULL AND truncated = false)), \n\tFOREIGN KEY(message_id) REFERENCES message_messages (id) ON DELETE CASCADE, \n\tCONSTRAINT ck_chat_thought_digest CHECK (length(source_digest) = 64)\n)",
    "CREATE TABLE social_activity_thoughts (\n\tid VARCHAR(64) NOT NULL, \n\towner_id VARCHAR(64) NOT NULL, \n\tworld_id VARCHAR(64) NOT NULL, \n\tactor_world_character_id VARCHAR(64) NOT NULL, \n\tsocial_event_id VARCHAR(64) NOT NULL, \n\tpublic_action_execution_id INTEGER, \n\tsource_kind VARCHAR(20) NOT NULL, \n\tsource_post_id VARCHAR(64), \n\tsource_digest VARCHAR(64) NOT NULL, \n\tthought_text TEXT, \n\tstatus VARCHAR(16) NOT NULL, \n\ttruncated BOOLEAN NOT NULL, \n\tcreated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tPRIMARY KEY (id), \n\tUNIQUE (social_event_id), \n\tCONSTRAINT ck_social_thought_content CHECK ((status = 'recorded' AND thought_text IS NOT NULL AND length(trim(thought_text)) BETWEEN 1 AND 280) OR (status <> 'recorded' AND thought_text IS NULL AND truncated = false)), \n\tFOREIGN KEY(source_post_id) REFERENCES posts (id) ON DELETE CASCADE, \n\tFOREIGN KEY(social_event_id) REFERENCES social_events (id) ON DELETE CASCADE, \n\tFOREIGN KEY(owner_id) REFERENCES users (id), \n\tCONSTRAINT ck_social_thought_source_kind CHECK (source_kind IN ('post_revision','action_event')), \n\tCONSTRAINT fk_social_thought_actor_world FOREIGN KEY(actor_world_character_id, world_id) REFERENCES world_characters (id, world_id), \n\tCONSTRAINT uq_social_thought_post_revision UNIQUE (source_post_id, source_digest), \n\tCONSTRAINT ck_social_thought_source CHECK ((source_kind = 'post_revision' AND source_post_id IS NOT NULL) OR (source_kind = 'action_event' AND source_post_id IS NULL)), \n\tCONSTRAINT ck_social_thought_digest CHECK (length(source_digest) = 64), \n\tCONSTRAINT uq_social_thought_execution UNIQUE (public_action_execution_id), \n\tCONSTRAINT ck_social_thought_status CHECK (status IN ('recorded','missing','invalid')), \n\tFOREIGN KEY(public_action_execution_id) REFERENCES agent_public_action_executions (id) ON DELETE CASCADE, \n\tFOREIGN KEY(world_id) REFERENCES worlds (id)\n)",
    'CREATE INDEX ix_social_thought_scope ON social_activity_thoughts (owner_id, world_id, actor_world_character_id, created_at)',
    'CREATE TABLE memory_episode_bundles (\n\tid VARCHAR(64) NOT NULL, \n\tscope_setting_id VARCHAR(64) NOT NULL, \n\tpolicy_version VARCHAR(40) NOT NULL, \n\tactivation_epoch VARCHAR(64) NOT NULL, \n\tcutoff_sequence INTEGER NOT NULL, \n\tmanifest_hash VARCHAR(64) NOT NULL, \n\tmanifest_json TEXT NOT NULL, \n\tresult_hash VARCHAR(64) NOT NULL, \n\tcreated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_episode_bundle_hash CHECK (length(manifest_hash) = 64), \n\tCONSTRAINT uq_episode_bundle_manifest UNIQUE (scope_setting_id, policy_version, activation_epoch, manifest_hash), \n\tFOREIGN KEY(scope_setting_id) REFERENCES memory_scope_settings (id) ON DELETE CASCADE\n)',
    'CREATE TABLE memory_episode_info (\n\tmemory_item_id VARCHAR(64) NOT NULL, \n\tbundle_id VARCHAR(64) NOT NULL, \n\tpolicy_version VARCHAR(40) NOT NULL, \n\tPRIMARY KEY (memory_item_id), \n\tFOREIGN KEY(memory_item_id) REFERENCES memory_items (id) ON DELETE CASCADE, \n\tFOREIGN KEY(bundle_id) REFERENCES memory_episode_bundles (id) ON DELETE CASCADE\n)',
    'CREATE INDEX ix_memory_episode_info_bundle_id ON memory_episode_info (bundle_id)',
    'CREATE TABLE memory_episode_units (\n\tid VARCHAR(64) NOT NULL, \n\tmemory_item_id VARCHAR(64) NOT NULL, \n\tunit_key VARCHAR(160) NOT NULL, \n\tunit_revision VARCHAR(64) NOT NULL, \n\tkind VARCHAR(32) NOT NULL, \n\tordinal INTEGER NOT NULL, \n\tcoverage VARCHAR(24) NOT NULL, \n\tchat_thought_message_id INTEGER, \n\tsocial_thought_id VARCHAR(64), \n\tthought_digest VARCHAR(64), \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_episode_unit_thought_owner CHECK (chat_thought_message_id IS NULL OR social_thought_id IS NULL), \n\tFOREIGN KEY(chat_thought_message_id) REFERENCES chat_message_thoughts (message_id) ON DELETE SET NULL, \n\tCONSTRAINT uq_episode_unit UNIQUE (memory_item_id, unit_key, unit_revision), \n\tFOREIGN KEY(social_thought_id) REFERENCES social_activity_thoughts (id) ON DELETE SET NULL, \n\tFOREIGN KEY(memory_item_id) REFERENCES memory_items (id) ON DELETE CASCADE\n)',
    'CREATE INDEX ix_memory_episode_units_memory_item_id ON memory_episode_units (memory_item_id)',
    'CREATE TABLE memory_episode_unit_evidence (\n\tunit_id VARCHAR(64) NOT NULL, \n\tevidence_id VARCHAR(64) NOT NULL, \n\tstart_offset INTEGER NOT NULL, \n\tend_offset INTEGER, \n\trole VARCHAR(32) NOT NULL, \n\tordinal INTEGER NOT NULL, \n\tPRIMARY KEY (unit_id, evidence_id, start_offset), \n\tFOREIGN KEY(evidence_id) REFERENCES memory_item_evidence (id) ON DELETE CASCADE, \n\tFOREIGN KEY(unit_id) REFERENCES memory_episode_units (id) ON DELETE CASCADE\n)',
    "CREATE TABLE memory_episode_processed_units (\n\tid VARCHAR(64) NOT NULL, \n\tbundle_id VARCHAR(64) NOT NULL, \n\tscope_setting_id VARCHAR(64) NOT NULL, \n\tpolicy_version VARCHAR(40) NOT NULL, \n\tactivation_epoch VARCHAR(64) NOT NULL, \n\tunit_key VARCHAR(160) NOT NULL, \n\tunit_revision VARCHAR(64) NOT NULL, \n\tdecision VARCHAR(16) NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(scope_setting_id) REFERENCES memory_scope_settings (id) ON DELETE CASCADE, \n\tCONSTRAINT ck_episode_processed_decision CHECK (decision IN ('used','skipped')), \n\tFOREIGN KEY(bundle_id) REFERENCES memory_episode_bundles (id) ON DELETE CASCADE, \n\tCONSTRAINT uq_episode_processed_unit UNIQUE (scope_setting_id, policy_version, activation_epoch, unit_key, unit_revision)\n)",
    'CREATE TABLE memory_episode_links (\n\tprior_item_id VARCHAR(64) NOT NULL, \n\tfollowing_item_id VARCHAR(64) NOT NULL, \n\tcreated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tPRIMARY KEY (prior_item_id, following_item_id), \n\tCONSTRAINT ck_episode_link_not_self CHECK (prior_item_id <> following_item_id), \n\tFOREIGN KEY(following_item_id) REFERENCES memory_items (id) ON DELETE CASCADE, \n\tFOREIGN KEY(prior_item_id) REFERENCES memory_items (id) ON DELETE CASCADE\n)',
    'CREATE INDEX ix_episode_link_following ON memory_episode_links (following_item_id)',
)

POSTGRESQL = (
    "CREATE TABLE chat_message_thoughts (\n\tmessage_id INTEGER NOT NULL, \n\trequest_id VARCHAR(64) NOT NULL, \n\tthought_text TEXT, \n\tstatus VARCHAR(16) NOT NULL, \n\ttruncated BOOLEAN NOT NULL, \n\tsource_digest VARCHAR(64) NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (message_id), \n\tCONSTRAINT ck_chat_thought_status CHECK (status IN ('recorded','missing','invalid')), \n\tFOREIGN KEY(request_id) REFERENCES chat_response_requests (request_id) ON DELETE CASCADE, \n\tCONSTRAINT uq_chat_thought_request UNIQUE (request_id), \n\tCONSTRAINT ck_chat_thought_content CHECK ((status = 'recorded' AND thought_text IS NOT NULL AND length(trim(thought_text)) BETWEEN 1 AND 280) OR (status <> 'recorded' AND thought_text IS NULL AND truncated = false)), \n\tFOREIGN KEY(message_id) REFERENCES message_messages (id) ON DELETE CASCADE, \n\tCONSTRAINT ck_chat_thought_digest CHECK (length(source_digest) = 64)\n)",
    "CREATE TABLE social_activity_thoughts (\n\tid VARCHAR(64) NOT NULL, \n\towner_id VARCHAR(64) NOT NULL, \n\tworld_id VARCHAR(64) NOT NULL, \n\tactor_world_character_id VARCHAR(64) NOT NULL, \n\tsocial_event_id VARCHAR(64) NOT NULL, \n\tpublic_action_execution_id INTEGER, \n\tsource_kind VARCHAR(20) NOT NULL, \n\tsource_post_id VARCHAR(64), \n\tsource_digest VARCHAR(64) NOT NULL, \n\tthought_text TEXT, \n\tstatus VARCHAR(16) NOT NULL, \n\ttruncated BOOLEAN NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tUNIQUE (social_event_id), \n\tCONSTRAINT ck_social_thought_content CHECK ((status = 'recorded' AND thought_text IS NOT NULL AND length(trim(thought_text)) BETWEEN 1 AND 280) OR (status <> 'recorded' AND thought_text IS NULL AND truncated = false)), \n\tFOREIGN KEY(source_post_id) REFERENCES posts (id) ON DELETE CASCADE, \n\tFOREIGN KEY(social_event_id) REFERENCES social_events (id) ON DELETE CASCADE, \n\tFOREIGN KEY(owner_id) REFERENCES users (id), \n\tCONSTRAINT ck_social_thought_source_kind CHECK (source_kind IN ('post_revision','action_event')), \n\tCONSTRAINT fk_social_thought_actor_world FOREIGN KEY(actor_world_character_id, world_id) REFERENCES world_characters (id, world_id), \n\tCONSTRAINT uq_social_thought_post_revision UNIQUE (source_post_id, source_digest), \n\tCONSTRAINT ck_social_thought_source CHECK ((source_kind = 'post_revision' AND source_post_id IS NOT NULL) OR (source_kind = 'action_event' AND source_post_id IS NULL)), \n\tCONSTRAINT ck_social_thought_digest CHECK (length(source_digest) = 64), \n\tCONSTRAINT uq_social_thought_execution UNIQUE (public_action_execution_id), \n\tCONSTRAINT ck_social_thought_status CHECK (status IN ('recorded','missing','invalid')), \n\tFOREIGN KEY(public_action_execution_id) REFERENCES agent_public_action_executions (id) ON DELETE CASCADE, \n\tFOREIGN KEY(world_id) REFERENCES worlds (id)\n)",
    'CREATE INDEX ix_social_thought_scope ON social_activity_thoughts (owner_id, world_id, actor_world_character_id, created_at)',
    'CREATE TABLE memory_episode_bundles (\n\tid VARCHAR(64) NOT NULL, \n\tscope_setting_id VARCHAR(64) NOT NULL, \n\tpolicy_version VARCHAR(40) NOT NULL, \n\tactivation_epoch VARCHAR(64) NOT NULL, \n\tcutoff_sequence INTEGER NOT NULL, \n\tmanifest_hash VARCHAR(64) NOT NULL, \n\tmanifest_json TEXT NOT NULL, \n\tresult_hash VARCHAR(64) NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_episode_bundle_hash CHECK (length(manifest_hash) = 64), \n\tCONSTRAINT uq_episode_bundle_manifest UNIQUE (scope_setting_id, policy_version, activation_epoch, manifest_hash), \n\tFOREIGN KEY(scope_setting_id) REFERENCES memory_scope_settings (id) ON DELETE CASCADE\n)',
    'CREATE TABLE memory_episode_info (\n\tmemory_item_id VARCHAR(64) NOT NULL, \n\tbundle_id VARCHAR(64) NOT NULL, \n\tpolicy_version VARCHAR(40) NOT NULL, \n\tPRIMARY KEY (memory_item_id), \n\tFOREIGN KEY(memory_item_id) REFERENCES memory_items (id) ON DELETE CASCADE, \n\tFOREIGN KEY(bundle_id) REFERENCES memory_episode_bundles (id) ON DELETE CASCADE\n)',
    'CREATE INDEX ix_memory_episode_info_bundle_id ON memory_episode_info (bundle_id)',
    'CREATE TABLE memory_episode_units (\n\tid VARCHAR(64) NOT NULL, \n\tmemory_item_id VARCHAR(64) NOT NULL, \n\tunit_key VARCHAR(160) NOT NULL, \n\tunit_revision VARCHAR(64) NOT NULL, \n\tkind VARCHAR(32) NOT NULL, \n\tordinal INTEGER NOT NULL, \n\tcoverage VARCHAR(24) NOT NULL, \n\tchat_thought_message_id INTEGER, \n\tsocial_thought_id VARCHAR(64), \n\tthought_digest VARCHAR(64), \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_episode_unit_thought_owner CHECK (chat_thought_message_id IS NULL OR social_thought_id IS NULL), \n\tFOREIGN KEY(chat_thought_message_id) REFERENCES chat_message_thoughts (message_id) ON DELETE SET NULL, \n\tCONSTRAINT uq_episode_unit UNIQUE (memory_item_id, unit_key, unit_revision), \n\tFOREIGN KEY(social_thought_id) REFERENCES social_activity_thoughts (id) ON DELETE SET NULL, \n\tFOREIGN KEY(memory_item_id) REFERENCES memory_items (id) ON DELETE CASCADE\n)',
    'CREATE INDEX ix_memory_episode_units_memory_item_id ON memory_episode_units (memory_item_id)',
    'CREATE TABLE memory_episode_unit_evidence (\n\tunit_id VARCHAR(64) NOT NULL, \n\tevidence_id VARCHAR(64) NOT NULL, \n\tstart_offset INTEGER NOT NULL, \n\tend_offset INTEGER, \n\trole VARCHAR(32) NOT NULL, \n\tordinal INTEGER NOT NULL, \n\tPRIMARY KEY (unit_id, evidence_id, start_offset), \n\tFOREIGN KEY(evidence_id) REFERENCES memory_item_evidence (id) ON DELETE CASCADE, \n\tFOREIGN KEY(unit_id) REFERENCES memory_episode_units (id) ON DELETE CASCADE\n)',
    "CREATE TABLE memory_episode_processed_units (\n\tid VARCHAR(64) NOT NULL, \n\tbundle_id VARCHAR(64) NOT NULL, \n\tscope_setting_id VARCHAR(64) NOT NULL, \n\tpolicy_version VARCHAR(40) NOT NULL, \n\tactivation_epoch VARCHAR(64) NOT NULL, \n\tunit_key VARCHAR(160) NOT NULL, \n\tunit_revision VARCHAR(64) NOT NULL, \n\tdecision VARCHAR(16) NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(scope_setting_id) REFERENCES memory_scope_settings (id) ON DELETE CASCADE, \n\tCONSTRAINT ck_episode_processed_decision CHECK (decision IN ('used','skipped')), \n\tFOREIGN KEY(bundle_id) REFERENCES memory_episode_bundles (id) ON DELETE CASCADE, \n\tCONSTRAINT uq_episode_processed_unit UNIQUE (scope_setting_id, policy_version, activation_epoch, unit_key, unit_revision)\n)",
    'CREATE TABLE memory_episode_links (\n\tprior_item_id VARCHAR(64) NOT NULL, \n\tfollowing_item_id VARCHAR(64) NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (prior_item_id, following_item_id), \n\tCONSTRAINT ck_episode_link_not_self CHECK (prior_item_id <> following_item_id), \n\tFOREIGN KEY(following_item_id) REFERENCES memory_items (id) ON DELETE CASCADE, \n\tFOREIGN KEY(prior_item_id) REFERENCES memory_items (id) ON DELETE CASCADE\n)',
    'CREATE INDEX ix_episode_link_following ON memory_episode_links (following_item_id)',
)

def upgrade():
    statements = SQLITE if op.get_bind().dialect.name == "sqlite" else POSTGRESQL
    for statement in statements:
        op.execute(statement)


def downgrade():
    op.drop_table('memory_episode_links')
    op.drop_table('memory_episode_processed_units')
    op.drop_table('memory_episode_unit_evidence')
    op.drop_table('memory_episode_units')
    op.drop_table('memory_episode_info')
    op.drop_table('memory_episode_bundles')
    op.drop_table('social_activity_thoughts')
    op.drop_table('chat_message_thoughts')
