"""Frozen additive consolidation trigger receipts, no data backfill."""
from alembic import op
revision = "20260917_0094"
down_revision = "20260916_0093"
branch_labels = None
depends_on = None

SQLITE = ('CREATE TABLE memory_consolidation_requests (\n\tid VARCHAR(64) NOT NULL, \n\tscope_setting_id VARCHAR(64) NOT NULL, \n\tkind VARCHAR(16) NOT NULL, \n\tidempotency_key VARCHAR(128) NOT NULL, \n\trequest_digest VARCHAR(64) NOT NULL, \n\tscheduled_for_utc DATETIME, \n\taccepted_at DATETIME NOT NULL, \n\tcutoff_sequence INTEGER NOT NULL, \n\tscope_version INTEGER NOT NULL, \n\tsettings_version INTEGER NOT NULL, \n\tprofile_version INTEGER NOT NULL, \n\tstate VARCHAR(24) NOT NULL, \n\tlast_code VARCHAR(80), \n\tcompleted_at DATETIME, \n\tcoalesced_to_request_id VARCHAR(64), \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_memory_request_slot UNIQUE (scope_setting_id, scheduled_for_utc), \n\tFOREIGN KEY(scope_setting_id) REFERENCES memory_scope_settings (id) ON DELETE CASCADE, \n\tCONSTRAINT uq_memory_request_key UNIQUE (scope_setting_id, idempotency_key), \n\tFOREIGN KEY(coalesced_to_request_id) REFERENCES memory_consolidation_requests (id)\n)', 'CREATE INDEX ix_memory_consolidation_requests_scope_setting_id ON memory_consolidation_requests (scope_setting_id)', 'CREATE INDEX ix_memory_consolidation_requests_state ON memory_consolidation_requests (state)', 'CREATE TABLE memory_consolidation_jobs (\n\trequest_id VARCHAR(64) NOT NULL, \n\tjob_id VARCHAR(64) NOT NULL, \n\tphase VARCHAR(24) NOT NULL, \n\tphase_started_at DATETIME, \n\tPRIMARY KEY (request_id, job_id), \n\tFOREIGN KEY(request_id) REFERENCES memory_consolidation_requests (id) ON DELETE CASCADE, \n\tFOREIGN KEY(job_id) REFERENCES memory_batch_runs (job_id) ON DELETE CASCADE\n)', 'CREATE INDEX ix_memory_consolidation_jobs_job_id ON memory_consolidation_jobs (job_id)')

POSTGRESQL = ('CREATE TABLE memory_consolidation_requests (\n\tid VARCHAR(64) NOT NULL, \n\tscope_setting_id VARCHAR(64) NOT NULL, \n\tkind VARCHAR(16) NOT NULL, \n\tidempotency_key VARCHAR(128) NOT NULL, \n\trequest_digest VARCHAR(64) NOT NULL, \n\tscheduled_for_utc TIMESTAMP WITH TIME ZONE, \n\taccepted_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tcutoff_sequence INTEGER NOT NULL, \n\tscope_version INTEGER NOT NULL, \n\tsettings_version INTEGER NOT NULL, \n\tprofile_version INTEGER NOT NULL, \n\tstate VARCHAR(24) NOT NULL, \n\tlast_code VARCHAR(80), \n\tcompleted_at TIMESTAMP WITH TIME ZONE, \n\tcoalesced_to_request_id VARCHAR(64), \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_memory_request_slot UNIQUE (scope_setting_id, scheduled_for_utc), \n\tFOREIGN KEY(scope_setting_id) REFERENCES memory_scope_settings (id) ON DELETE CASCADE, \n\tCONSTRAINT uq_memory_request_key UNIQUE (scope_setting_id, idempotency_key), \n\tFOREIGN KEY(coalesced_to_request_id) REFERENCES memory_consolidation_requests (id)\n)', 'CREATE INDEX ix_memory_consolidation_requests_scope_setting_id ON memory_consolidation_requests (scope_setting_id)', 'CREATE INDEX ix_memory_consolidation_requests_state ON memory_consolidation_requests (state)', 'CREATE TABLE memory_consolidation_jobs (\n\trequest_id VARCHAR(64) NOT NULL, \n\tjob_id VARCHAR(64) NOT NULL, \n\tphase VARCHAR(24) NOT NULL, \n\tphase_started_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (request_id, job_id), \n\tFOREIGN KEY(request_id) REFERENCES memory_consolidation_requests (id) ON DELETE CASCADE, \n\tFOREIGN KEY(job_id) REFERENCES memory_batch_runs (job_id) ON DELETE CASCADE\n)', 'CREATE INDEX ix_memory_consolidation_jobs_job_id ON memory_consolidation_jobs (job_id)')

def upgrade():
    for statement in SQLITE if op.get_bind().dialect.name == "sqlite" else POSTGRESQL:
        op.execute(statement)

def downgrade():
    op.drop_table("memory_consolidation_jobs")
    op.drop_table("memory_consolidation_requests")
