import { GENERATION_PROFILES, DEFAULT_GENERATION_PROFILE } from "@/config/generation-profiles";
export const MESSAGE_GOOGLE_GEMINI_MODELS = GENERATION_PROFILES;
export const DEFAULT_MESSAGE_GOOGLE_MODEL = DEFAULT_GENERATION_PROFILE;
