"""Named source reads; ORM rows stay attached to the supplied Session.

The heterogeneous result shapes are the existing source rows/results. Memory
interprets them immediately; collaborators do not open sessions or commit.
"""

from __future__ import annotations
from typing import Any, Protocol
from sqlalchemy.orm import Session
from app.domains.memory.contracts.scope import MemoryScope


class SourcePost(Protocol):
    id: str


class MemorySourceQueries(Protocol):
    def chat_message_pair(self, session: Session, message_id: Any) -> Any: ...
    def post_row(self, session: Session, source_id: Any) -> Any: ...
    def reply_parent(self, session: Session, post: Any) -> Any: ...
    def reaction_row(self, session: Session, reaction_id: Any) -> Any: ...
    def reaction_post(self, session: Session, reaction: Any) -> Any: ...
    def social_event_row(self, session: Session, source_id: Any) -> Any: ...
    def activity_beat_row(self, session: Session, source_id: Any) -> Any: ...
    def relationship_change_row(self, session: Session, source_id: Any) -> Any: ...
    def relationship_social_event(self, session: Session, change: Any) -> Any: ...
    def joint_activity_row(self, session: Session, source_id: Any) -> Any: ...
    def joint_participants(self, session: Session, joint: Any) -> Any: ...
    def post_observation(
        self, session: Session, scope: MemoryScope, post: Any
    ) -> Any: ...
    def event_post_ids(self, session: Session, event_id: Any) -> Any: ...
    def event_observation(
        self, session: Session, source_post_ids: Any, scope: MemoryScope
    ) -> Any: ...
    def active_participant_ids(
        self, session: Session, ids: Any, world_id: Any
    ) -> Any: ...
    def block_id(
        self, session: Session, world_id: Any, subject: Any, counterpart: Any
    ) -> Any: ...
    def read_subjective_source(
        self, session: Session, scope: MemoryScope, *, source_type: str, source_id: str
    ) -> tuple[str, str] | None: ...
