from app.domains.identity.repository.credentials import get_credential, get_default_credential
from sqlalchemy import select
from sqlalchemy.orm import Session
from app.runtime.persistence.model_registration import register_models
register_models()
from app.domains.relationships.constants import (RELATIONSHIP_POINT_KINDS, RELATIONSHIP_POINT_PENDING, RELATIONSHIP_POINT_SELECTED, RELATIONSHIP_POINT_CONSUMED, RELATIONSHIP_POINT_EXPIRED, RELATIONSHIP_POINT_FAILED, RELATIONSHIP_POINT_ACTIVE_STATUSES)
from app.domains.relationships.utils.points import (relationship_point_pair_key, relationship_point_source_signature, relationship_point_chain_id, _relationship_point_payload)
from app.domains.relationships.repository.points import count_relationship_points_for_pair_since
from app.domains.relationships.service.points import (create_relationship_point, expire_relationship_points, list_pending_relationship_points, mark_relationship_point_selected, release_relationship_point_selection, mark_relationship_point_consumed, mark_relationship_point_replied, mark_relationship_point_failed)
