"""Single supported entrypoint for World Creator use cases.

API routes and other domains import this module instead of reaching into the
SQLAlchemy adapter. Compatibility modules may re-export these names while the
remaining L3 boundaries migrate in later pull requests.
"""

from app.domains.worlds.infrastructure.sqlalchemy_world_creator import (
    WorldArchivedError,
    WorldBannerValidationError,
    WorldCreatorRoleRequiredError,
    WorldDefinitionIncompleteError,
    WorldDefinitionValidationError,
    WorldMembershipRequiredError,
    WorldNotFoundError,
    WorldOwnerRoleRequiredError,
    WorldRowVersionConflictError,
    WorldServiceError,
    WorldSeedOutcome,
    archive_world,
    create_world,
    get_active_membership,
    get_creator_context,
    get_generation_context,
    is_enabled_world_role,
    get_world,
    get_world_read,
    publish_world,
    remove_world_banner,
    reschedule_world_autonomy_slots,
    seed_world,
    require_creator_access,
    require_owner_access,
    require_world_read_access,
    update_world,
    upload_world_banner,
    validate_world_definition,
)
from app.domains.worlds.infrastructure.generation_context import (
    build_world_generation_context,
)
from app.domains.worlds.infrastructure.definition_repository import (
    WORLD_CONTRACT_VERSION,
    refresh_world_contract,
    world_contract_hash,
)
from app.domains.worlds.domain.reserved_roles import (
    NO_SPECIFIC_ROLE_DESCRIPTION,
    NO_SPECIFIC_ROLE_KEY,
    NO_SPECIFIC_ROLE_NAME,
    NO_SPECIFIC_ROLE_PORTABLE_REF,
    is_canonical_no_specific_role,
)
from app.domains.worlds.infrastructure.sqlalchemy_reserved_roles import (
    ReservedWorldRoleConflictError,
    ensure_no_specific_role,
)
from app.domains.worlds.api.schemas import (
    WorldDaypartProfileInput,
    WorldDraftCreate,
    WorldGenerationContextRead,
    WorldGlossaryTermInput,
    WorldPlaceInput,
    WorldRoleInput,
    WorldRuleInput,
)
from app.domains.worlds.infrastructure.sqlalchemy_models import (
    JSON_DOCUMENT,
    World,
    WorldMembership,
    WorldRole,
)

__all__ = [
    "JSON_DOCUMENT",
    "NO_SPECIFIC_ROLE_DESCRIPTION",
    "NO_SPECIFIC_ROLE_KEY",
    "NO_SPECIFIC_ROLE_NAME",
    "NO_SPECIFIC_ROLE_PORTABLE_REF",
    "ReservedWorldRoleConflictError",
    "WorldArchivedError",
    "WorldBannerValidationError",
    "WorldCreatorRoleRequiredError",
    "WorldDefinitionIncompleteError",
    "WorldDefinitionValidationError",
    "WorldMembershipRequiredError",
    "WorldNotFoundError",
    "WorldOwnerRoleRequiredError",
    "WorldRowVersionConflictError",
    "WorldServiceError",
    "WorldSeedOutcome",
    "WORLD_CONTRACT_VERSION",
    "World",
    "WorldDaypartProfileInput",
    "WorldDraftCreate",
    "WorldGenerationContextRead",
    "WorldGlossaryTermInput",
    "WorldMembership",
    "WorldPlaceInput",
    "WorldRoleInput",
    "WorldRuleInput",
    "WorldRole",
    "archive_world",
    "build_world_generation_context",
    "create_world",
    "get_active_membership",
    "get_creator_context",
    "get_generation_context",
    "is_enabled_world_role",
    "get_world",
    "get_world_read",
    "ensure_no_specific_role",
    "is_canonical_no_specific_role",
    "publish_world",
    "remove_world_banner",
    "reschedule_world_autonomy_slots",
    "refresh_world_contract",
    "seed_world",
    "require_creator_access",
    "require_owner_access",
    "require_world_read_access",
    "update_world",
    "upload_world_banner",
    "validate_world_definition",
    "world_contract_hash",
]
