"""Temporary compatibility exports for unmigrated World consumers.

New calls use worlds.service, worlds.schemas and worlds.contracts. ORM exports
remain here only for the individually tracked WC/Package/Routines consumers;
canonical World implementations never import this module.
"""

from app.domains.worlds.service.creator import (
    WorldArchivedError,
    WorldBannerValidationError,
    WorldCreatorRoleRequiredError,
    WorldDefinitionIncompleteError,
    WorldDefinitionValidationError,
    WorldMembershipRequiredError,
    WorldNotFoundError,
    WorldOwnerRoleRequiredError,
    WorldRowVersionConflictError,
    WorldServiceError,
    WorldSeedOutcome,
    archive_world,
    create_world,
    get_active_membership,
    get_creator_context,
    get_generation_context,
    is_enabled_world_role,
    get_world,
    get_world_read,
    publish_world,
    remove_world_banner,
    reschedule_world_autonomy_slots,
    seed_world,
    require_creator_access,
    require_owner_access,
    require_world_read_access,
    update_world,
    upload_world_banner,
    validate_world_definition,
)
from app.domains.worlds.service.generation_context import (
    build_world_generation_context,
)
from app.domains.worlds.service.definition import (
    WORLD_CONTRACT_VERSION,
    refresh_world_contract,
    world_contract_hash,
)
from app.domains.worlds.contracts import (
    NO_SPECIFIC_ROLE_DESCRIPTION,
    NO_SPECIFIC_ROLE_KEY,
    NO_SPECIFIC_ROLE_NAME,
    NO_SPECIFIC_ROLE_PORTABLE_REF,
    is_canonical_no_specific_role,
)
from app.domains.worlds.service.reserved_roles import (
    ReservedWorldRoleConflictError,
    ensure_no_specific_role,
)
from app.domains.worlds.schemas import (
    WorldDaypartProfileInput,
    WorldDraftCreate,
    WorldGenerationContextRead,
    WorldGlossaryTermInput,
    WorldPlaceInput,
    WorldRoleInput,
    WorldRuleInput,
)
from app.domains.worlds.models import (
    JSON_DOCUMENT,
    World,
    WorldMembership,
    WorldRole,
)

__all__ = [
    "JSON_DOCUMENT",
    "NO_SPECIFIC_ROLE_DESCRIPTION",
    "NO_SPECIFIC_ROLE_KEY",
    "NO_SPECIFIC_ROLE_NAME",
    "NO_SPECIFIC_ROLE_PORTABLE_REF",
    "ReservedWorldRoleConflictError",
    "WorldArchivedError",
    "WorldBannerValidationError",
    "WorldCreatorRoleRequiredError",
    "WorldDefinitionIncompleteError",
    "WorldDefinitionValidationError",
    "WorldMembershipRequiredError",
    "WorldNotFoundError",
    "WorldOwnerRoleRequiredError",
    "WorldRowVersionConflictError",
    "WorldServiceError",
    "WorldSeedOutcome",
    "WORLD_CONTRACT_VERSION",
    "World",
    "WorldDaypartProfileInput",
    "WorldDraftCreate",
    "WorldGenerationContextRead",
    "WorldGlossaryTermInput",
    "WorldMembership",
    "WorldPlaceInput",
    "WorldRoleInput",
    "WorldRuleInput",
    "WorldRole",
    "archive_world",
    "build_world_generation_context",
    "create_world",
    "get_active_membership",
    "get_creator_context",
    "get_generation_context",
    "is_enabled_world_role",
    "get_world",
    "get_world_read",
    "ensure_no_specific_role",
    "is_canonical_no_specific_role",
    "publish_world",
    "remove_world_banner",
    "reschedule_world_autonomy_slots",
    "refresh_world_contract",
    "seed_world",
    "require_creator_access",
    "require_owner_access",
    "require_world_read_access",
    "update_world",
    "upload_world_banner",
    "validate_world_definition",
    "world_contract_hash",
]
