"""Frozen additive V2 activity schema; existing rows are preserved."""
from app.runtime.migrations.sqlite_versions.contracts import SqliteMigrationDeltaError
MUTABLE_IDENTITY_TABLES = frozenset(('world_character_activity_states', 'world_character_state_receipts', 'activity_engine_policies', 'activity_graph_runs'))
DDL = ["\nCREATE TABLE world_character_activity_states (\n\tworld_character_id VARCHAR(64) NOT NULL, \n\tworld_id VARCHAR(64) NOT NULL, \n\tmood VARCHAR(24), \n\tmood_intensity INTEGER, \n\tstate_note VARCHAR(160), \n\tversion INTEGER NOT NULL, \n\tchanged_at DATETIME, \n\tconfirmed_at DATETIME, \n\torigin VARCHAR(100), \n\tPRIMARY KEY (world_character_id), \n\tCONSTRAINT ck_activity_state_version CHECK (version >= 1), \n\tCONSTRAINT ck_activity_state_intensity CHECK (mood_intensity IS NULL OR (mood_intensity >= 0 AND mood_intensity <= 100)), \n\tCONSTRAINT ck_activity_state_complete CHECK ((mood IS NULL AND mood_intensity IS NULL AND state_note IS NULL) OR (mood IS NOT NULL AND mood_intensity IS NOT NULL AND state_note IS NOT NULL)), \n\tFOREIGN KEY(world_character_id, world_id) REFERENCES world_characters (id, world_id) ON DELETE CASCADE, \n\tCONSTRAINT ck_activity_state_mood CHECK (mood IS NULL OR mood IN ('neutral','curious','joyful','hopeful','calm','concerned','frustrated','sad','embarrassed'))\n)\n\n", '\nCREATE TABLE world_character_state_receipts (\n\tdecision_key VARCHAR(64) NOT NULL, \n\tworld_character_id VARCHAR(64) NOT NULL, \n\tworld_id VARCHAR(64) NOT NULL, \n\tactivity_id VARCHAR(100) NOT NULL, \n\toutcome VARCHAR(40) NOT NULL, \n\texpected_version INTEGER NOT NULL, \n\tresulting_version INTEGER NOT NULL, \n\tsource_keys JSON NOT NULL, \n\tjudged_at DATETIME NOT NULL, \n\tPRIMARY KEY (decision_key), \n\tFOREIGN KEY(world_character_id, world_id) REFERENCES world_characters (id, world_id) ON DELETE CASCADE\n)\n\n', 'CREATE INDEX ix_world_character_state_receipts_world_character_id ON world_character_state_receipts (world_character_id)', "\nCREATE TABLE activity_engine_policies (\n\tscope_key VARCHAR(100) NOT NULL, \n\tworld_id VARCHAR(64), \n\tworld_character_id VARCHAR(64), \n\tengine VARCHAR(32) NOT NULL, \n\tversion INTEGER NOT NULL, \n\tupdated_at DATETIME NOT NULL, \n\tPRIMARY KEY (scope_key), \n\tFOREIGN KEY(world_character_id) REFERENCES world_characters (id) ON DELETE CASCADE, \n\tCONSTRAINT ck_activity_engine_version CHECK (version >= 1), \n\tCONSTRAINT ck_activity_engine CHECK (engine IN ('current','personalized_graph_v2')), \n\tFOREIGN KEY(world_id) REFERENCES worlds (id) ON DELETE CASCADE\n)\n\n", '\nCREATE TABLE activity_graph_runs (\n\tactivity_id VARCHAR(100) NOT NULL, \n\tworld_id VARCHAR(64) NOT NULL, \n\tworld_character_id VARCHAR(64) NOT NULL, \n\tengine VARCHAR(32) NOT NULL, \n\tcontract_version INTEGER NOT NULL, \n\tstatus VARCHAR(32) NOT NULL, \n\tstage VARCHAR(80) NOT NULL, \n\tresult JSON, \n\tstarted_at DATETIME NOT NULL, \n\tfinished_at DATETIME, \n\tPRIMARY KEY (activity_id), \n\tFOREIGN KEY(world_character_id, world_id) REFERENCES world_characters (id, world_id) ON DELETE CASCADE\n)\n\n', 'CREATE INDEX ix_activity_graph_runs_world_character_id ON activity_graph_runs (world_character_id)']

def capture_delta(connection):
    return frozenset(r[0] for r in connection.exec_driver_sql("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'"))

def upgrade(connection):
    for statement in DDL:
        connection.exec_driver_sql(statement)

def verify_delta(connection, before):
    if capture_delta(connection) != before | MUTABLE_IDENTITY_TABLES:
        raise SqliteMigrationDeltaError("activity_schema_inventory_invalid")
    for table in MUTABLE_IDENTITY_TABLES:
        if connection.exec_driver_sql(f"SELECT count(*) FROM {table}").scalar_one():
            raise SqliteMigrationDeltaError("activity_schema_must_start_empty")
