POLLINATIONS_IMAGE_MODEL_FLUX_KLEIN = "klein"
POLLINATIONS_IMAGE_MODEL_FLUX_SCHNELL = "flux"
POLLINATIONS_IMAGE_MODEL_ZIMAGE = "zimage"
POLLINATIONS_IMAGE_MODEL_PRUNA_EDIT = "p-image-edit"
POLLINATIONS_IMAGE_MODEL_SANA = "sana"
REPLICATE_IMAGE_MODEL_ZIMAGE_TURBO_LORA = "replicate-zimage-turbo-lora"
REPLICATE_IMAGE_MODEL_PRUNA_EDIT = "replicate-p-image-edit"
POLLINATIONS_IMAGE_MODEL_OPTIONS = {
    POLLINATIONS_IMAGE_MODEL_FLUX_KLEIN,
    POLLINATIONS_IMAGE_MODEL_FLUX_SCHNELL,
    POLLINATIONS_IMAGE_MODEL_ZIMAGE,
    POLLINATIONS_IMAGE_MODEL_PRUNA_EDIT,
    POLLINATIONS_IMAGE_MODEL_SANA,
}
REPLICATE_IMAGE_MODEL_OPTIONS = {
    REPLICATE_IMAGE_MODEL_ZIMAGE_TURBO_LORA,
    REPLICATE_IMAGE_MODEL_PRUNA_EDIT,
}
IMAGE_MODEL_OPTIONS = (
    POLLINATIONS_IMAGE_MODEL_OPTIONS | REPLICATE_IMAGE_MODEL_OPTIONS
)
USER_IMAGE_MODEL_OPTIONS = REPLICATE_IMAGE_MODEL_OPTIONS
DEFAULT_POLLINATIONS_IMAGE_MODEL = POLLINATIONS_IMAGE_MODEL_FLUX_KLEIN
DEFAULT_USER_IMAGE_MODEL = REPLICATE_IMAGE_MODEL_ZIMAGE_TURBO_LORA

DEFAULT_MAX_IMAGES_PER_DAY = 10
MAX_IMAGES_PER_DAY = 20

POST_IMAGE_TARGET_SIZE = (1024, 768)
POST_IMAGE_TARGET_MAX_BYTES = 900_000
POST_IMAGE_WEBP_QUALITY_STEPS = (78, 70, 62)
